# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: vendas_development
  username: root
  password: "rafael@123"

test:
  adapter: mysql2
  database: vendas_test
  username: root
  password: "rafael@123"

production:
  adapter: mysql2
  database: vendas_production
  username: root
  password: "rafael@123"
